sudo: false

language: d

d:
  - dmd
  - ldc

packages:
  - pkg-config
  - liblapack-dev 

install:
  - pyenv global system 3.6
  - pip3 install 'meson>=0.45'
  - mkdir .ntmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o .ntmp/ninja-linux.zip
  - unzip .ntmp/ninja-linux.zip -d .ntmp
before_script:
  - export PATH=$PATH:$PWD/.ntmp

script:
  - dub build --build=unittest -c blas
  - dub --root examples/gesv -c travis
  - meson build && cd build && ninja -j4 && ninja test -v && cd ..
